### ISSUE TITLE
Homepage is missing content

### ISSUE THREAD

**Issue by AdamDIOM** [ImMattDavison/LifesABeach#2]
There is nothing on the homepage, and the background image is not available.

**Comment by ImMattDavison** [comment]
Hey @AdamDIOM 

What is the background image to be?

**Comment by AdamDIOM** [comment]
> Hey @AdamDIOM
> 
> What is the background image to be?

This is it! Taken by myself, _this week_!
![IMG_9502](https://github.com/ImMattDavison/LifesABeach/assets/66436400/936f6ccb-135d-4ded-95a5-487f2c7c816e)

**Comment by AdamDIOM** [comment]
Great starter content on the homepage. Closing this issue, please create a new one for future content.
