### ISSUE TITLE
Branding colours

### ISSUE THREAD

**Issue by ImMattDavison** [ImMattDavison/LifesABeach#3]
Hey! 

What colours do we want to use for the branding? 

Some hex codes would be appreciated. 

Thanks in advance!

**Comment by AdamDIOM** [comment]
> What colours do we want to use for the branding?

I'm thinking beach-like colours, possibly combined with rainbows.

> Some hex codes would be appreciated.

Here we go!
- **Sky Blue** #6199e8
- **Dull Sand** #b3b6a1
- **Naval Navy** #161f30
- **HiViz Green** #e4fbb6

What do you think of these?

**Comment by ImMattDavison** [comment]
These look great!

What do you think of these? 
![image](https://github.com/ImMattDavison/LifesABeach/assets/80921257/85dd1837-89e1-4134-bb6d-4275db43d329)

rgb(240,152,25) & rgb(251,126,253)

**Comment by AdamDIOM** [comment]
They are nice, however I think it takes away from the beach theme a bit, looks _very_ artificial. Perhaps we can use these as accent colours elsewhere? However, they do fit nicely with the Pride/rainbows theme. I think we need to code some pages and see what looks best.

Also - do you prefer Hex or RGB colours as I notice you have used RGB in yours.

**Comment by AdamDIOM** [comment]
Closing issue as colours are sorted.
