### ISSUE TITLE
How do we want to store the API data?

### ISSUE THREAD

**Issue by ImMattDavison** [ImMattDavison/LifesABeach#4]
Do we want to store API data in a set of JSON files in the public directory or do we want to store them in a database??

**Comment by AdamDIOM** [comment]
In terms of simplicity, JSON is probably the easiest to access, however databases are much more secure and arguably can be more user-friendly to update with a dashboard.

**Comment by ImMattDavison** [comment]
> In terms of simplicity, JSON is probably the easiest to access, however databases are much more secure and arguably can be more user-friendly to update with a dashboard.

I think JSON may be the best choice this weekend just for the sake of simplicity? What do you think?

**Comment by AdamDIOM** [comment]
I agree with this, closing this issue as the query is resolved.
